name: 'Build and Test Java with Maven'
description: 'A reusable GitHub Action to build and test Java projects using Maven'
inputs:
  java-version:
    description: 'The Java version to use'
    required: false
    default: '17'
runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Build with Maven
      id: build
      run: mvn -B package --file pom.xml
      shell: bash

    - name: Run tests with Maven
      id: test
      run: mvn test
      shell: bash

  outputs:
    success:
      description: 'Indicates whether the process was successful'
      value: ${{ steps.build.outcome == 'success' && steps.test.outcome == 'success' }}